remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: ComicContours
description: CS 426 Senior Project Team 7, Spring 2023, UNR, CSE Department
logo: ./logo.jpg
email: brbrhiannon@aol.com
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Senior-ProjectTeam07/ComicContours

navigation:
  - name: Home Page
    link: ./
    sublist:
      - name: Usage
        link: ./#usage
      - name: Customizing
        link: ./#customizing
      - name: Customizing Sidebar
        link: ./#customizing-sidebar
      - name: Navigation
        link: ./#navigation
      - name: Example
        link: ./#example
      - name: Stylesheet
        link: ./#stylesheet
      - name: Credits
        link: ./#credits
  - name: Sample
    link: ./another-page.html
    sublist:
      - name: Image
        link: ./another-page.html#small-image
