remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: ComicContours
description: CS 426 Senior Project Team 7, Spring 2023, UNR, CSE Department
logo: ./current.jpg
email: brbrhiannon@aol.com
favicon: false
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Senior-ProjectTeam07/ComicContours

navigation:
  - name: Home Page
    link: ./
